"""empty message

Revision ID: 42348da9f455
Revises: 51fd99c58540
Create Date: 2021-11-03 01:14:56.497761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42348da9f455'
down_revision = '51fd99c58540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
